spring:
  profiles: default
  application:
      name: my-app
  cloud:
    config:
      uri: http://localhost:8080
  data:
    mongodb:
      database: scarry_plan

server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/