spring:
  profiles: default
  application:
    name: admin-made
  data:
    mongodb:
      database: homemade_user
server:
 port: 9092

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/